export const ui = {
  dashboardTitle: 'Dashboard Overview',
  dashboardSubtitle: 'Monitor your digital assets and system health',
  assetListTitle: 'Asset Library',
  uploadAsset: 'Upload Asset',
  cancel: 'Cancel',
  save: 'Save Changes',
  edit: 'Edit',
  view: 'View Details',
  delete: 'Delete',
  download: 'Download',
  share: 'Share',
  actions: 'Actions',

  filterByName: 'Search by name...',
  status: 'Status',
  approved: 'Approved',
  pending: 'Pending',
  underReview: 'Under Review',
  image: 'Image',
  video: 'Video',
  document: 'Document',
  audio: 'Audio',
  noAssetsFound: 'No assets found',
  tryAdjustingFilters: "Try adjusting your search or filters to find what you're looking for.",
};
