apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-namespace.yaml
  - 01-config.yaml
  - 02-infra.yaml
  - 03-apps.yaml
  - 04-gateway.yaml
  - 05-hpa.yaml
  - monitoring/prometheus.yaml
  - monitoring/grafana.yaml
