{
 "title": "DAM Main Dashboard",
 "panels": [
  { "title": "Worker Service Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Worker Scale",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(up{pod=~\"worker-.*\", namespace=\"dam\"})"
    }
   ]
  },
  {
   "title": "Active Jobs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(dam_worker_jobs_processing{namespace=\"dam\"})"
    }
   ]
  },
  {
   "title": "Worker CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{pod=~\"worker-.*\",namespace=\"dam\"}[5m]))"
    }
   ]
  }
 ]
}
{
 "title": "DAM Performance Testing",
 "panels": [
  {
   "title": "Pod CPU Utilization (%)",
   "type": "timeseries",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"dam\"}[5m])) by (pod)"
    }
   ]
  }
 ]
}
{
 "title": "DAM Logs Dashboard",
 "panels": [
  {
   "title": "DAM Application Logs",
   "type": "logs",
   "targets": [
    {
     "expr": "{namespace=\"dam\"}"
    }
   ]
  }
 ]
}